### ISSUE TITLE
Add specific slack channel to all projects

### ISSUE THREAD

**Issue by alessbn** [systers/ossprojects#12]
I think it's a good idea to add specific channel to all the projects so new contributors will know where they can ask questions about the project.

Thank you! :smile:

**Comment by anubhakushwaha** [comment]
@alessbn Hey hi,welcome to the community :) There are slack channels for each project.Please join http://systers.io/slack-systers-opensource/ and navigate to the channel of the interested project :)

**Comment by arunikayadav42** [comment]
I am unable to connect with the slack channel please help me out!!
