### ISSUE TITLE
Faulty hyperlink on Systers-Portal Wiki

### ISSUE THREAD

**Issue by mansimarkaur** [systers/ossprojects#14]
The link to [screenshots of community pages on old website](http://systers.org/systers-dev/doku.php/portal) on the [Systers-Portal](https://github.com/systers/ossprojects/wiki/Systers-Portal) wiki gives a 404.
Could you please take a look, @MeepyMay ?

**Comment by NjeriNjoroge** [comment]
Hello, i'm Grace and i'm participating in Outreachy internship. I'm studying Android Development which I will be graduating in November.
How do i get started on working on this issue?

**Comment by MeepyMay** [comment]
@mansimarkaur When Systers updated Mailman this year, the wiki domain was changed. Here's the correct link: http://wiki.systers.org/open-source/doku.php/portal

@NjeriNjoroge Can you compile a list of broken links here? I'll work on the other opened issues as well.
