### ISSUE TITLE
iOS app implementation 

### ISSUE THREAD

**Issue by manas15** [systers/ossprojects#2]
Hey Everyone 

I'm a 3rd year Computer Software Engineering student at Delhi Technological University. I have been into iOS development for some time now. I also have an experience of working with IBM as an iOS developer. 

I wish to build the iOS app PeaceTrack with swift 2.0 as the part of GSOC 2016.
Can someone guide me how to go about it. This is my first time with Google Summer Of Code.

Also the organisation(Anita Borg Institute) backing this project encourages participation of women in code. Which is great. But I have a doubt. Can men also participate in contributing to these projects? 

Cheers 
Manas Sharma

**Comment by MeepyMay** [comment]
Hello @manas15 

I know you've talked to Bruno, so I hope your doubts are cleared. 

Both men and women are accepted into GSoC.

**Comment by manas15** [comment]
Thanks @MeepyMay  :)
