### ISSUE TITLE
Android development Environment

### ISSUE THREAD

**Issue by vasilisaz** [systers/ossprojects#3]
Hi @rosariorobinson @nhutch01  @MeepyMay 
I am Vasilisa Zhuravlev, pursuing a BSc in Computer Science from the University of York, England. I am a 2016 GSoC aspirant and would like to do a project on the Peacetrack project, developing the Android environment. I also would like to get involved with the Systers and ABI.  I will like to know if there are any prerequisites to contribute to it?

Thank your for your reply,

Sincerely,
Vas

**Comment by rajatvijay** [comment]
Hi I am Rajat Vijay, I would like to do the Photo Language Translation web-app as my GSoC projcet. I would also like to get involved with the Systers and the ABI. I will like to know if there any short projects that I can get involved with to showcase my skill in Ruby on Rails framework.

Thanks for your reply!

Rajat Vijay

**Comment by MeepyMay** [comment]
@rajatvijay 

Hello! Please sign up on our Slack channel here: [systers.io/slack-systers-opensource/](http://systers.io/slack-systers-opensource/)

I will send you an email with many resources that point to who the potential mentors are for Photo Language Translation.

There's a #language-translation channel you should join to get more information.

Thank you for showing interest in participating with Systers at GSoC!

**Comment by Jagruti1010** [comment]
@rosariorobinson @MeepyMay @nhutch01  , I am an Android Developer , pursuing B.Tech , final year. I have done Internship with many companies for Android development , I want to contribute a material designed ConApp , for Systers with the use of various Widgets and Layouts. Please give me Ideas about contributing for app.

Thank You for Reply , 
Sincerely
Jagruti Khokhar
