### ISSUE TITLE
Doubt Regrading Gsoc'16

### ISSUE THREAD

**Issue by Devmassnk** [systers/ossprojects#4]
@MeepyMay 
Is anitaborg institute only take womens in gsoc as i have seen in past gsoc no male candidate selected? Is anitaborg  institute  prefer women over men in gsoc?

**Comment by MeepyMay** [comment]
Hello @Devmassnk!

Not at all! 

Here's a list of past applicants: [Systers GSoC 2015](http://systers.org/systers-dev/doku.php/gsoc_2015_student_profiles)

Bruno and Ilo are men who participated in last year's GSoC that are now mentoring for GSoC this year.

You can sign up for our Slack channel here: [Systers OpenSource Slack](http://systers.io/slack-systers-opensource/)

They are active on Slack. Bruno works on Malaria, iOS and Ilo works on PCSA.

Let me know if you have more questions. I'll see you on Slack. :)
