### ISSUE TITLE
Direction for Malaria Web App - Peace Corps Project

### ISSUE THREAD

**Issue by arishuynhvan** [systers/ossprojects#5]
Hi, I am interested in the web application of the project Malaria Prevention (https://github.com/systers/ossprojects/wiki/Malaria-Prevention) under Peace Corps organization. I am Tu An, a Biomedical Engineering sophomore minoring in Computer Science, National University of Singapore. I have picked up my programming skills (C,C++, Java) in uni and started to learn web development with FreeCodeCamp since last year to learn more about HTML/CSS/Javascript, with some understanding of jQuery and Node.js. The framework which I am more familiar with is Meteor.js. (https://www.freecodecamp.com/arishuynhvan). I have been using Github for more than a year, although I have not been overly active there, since I mainly use it for uploading my personal projects.

I hope to check with you if the project will be mainly building a responsive front-end of the Malaria Prevention WebApp, or will it include the backend (database, access, retrieval, modification) as well? I had a little knowledge of mySQL, but I believe MongoDB will be more suitable if I hope to develop this web app using Meteor.js. Please kindly answer my queries and advise me on a good place to start with this project (i.e. should I develop the UI according to the prototype before submitting the proposal? Or what other technical requirements should I consider as well?).

Thank you for your kind attention. I truly look forward to hearing from you soon.

Regards

Tu An

**Comment by MeepyMay** [comment]
Hello! Please sign up on our Slack channel here: [systers.io/slack-systers-opensource/](systers.io/slack-systers-opensource/)

**Comment by Rupinderwadali** [comment]
Hello Developers,
I am very interested in contributing to this project. I also started working on this project. The basic requirement of this project is node.js for backend and React.js for the frontend and I have the knowledge of node.js (express.js and hapi) for backend and React.js for the frontend and comfortable with MongoDB and NoSQL database, will use as per the requirement. Also familiar with the meteor.js (MVC framework).In fact currently, I am working on these technologies. The UI/UX design of the App is already done. Need the assistance of mentor for further implementation. @MeepyMay Should I continue work on it? Who are the mentors of the project?
Thanks:).
