### ISSUE TITLE
PCSA Android

### ISSUE THREAD

**Issue by vertata** [systers/ossprojects#6]
Hello! I'm interected in the Peace Corps Safety App (Android Development Environment)!  I'm 4th year student of the Faculty of Applied Mathematics, Oles Honchar Dnipropetrovsk National University, Ukraine. I have programming skills with Java, JavaFX, have some experience  in development of applications for Android and work with Android Stuio and Genimotion . Also I have knowleges of databases like mySQL, PostgresSQL and H2. I did'n use Git before, but I'm learning it now for using in near future :)
Could you possibly tell me, where I can read more information about this project? And where I can ask about proposal and write it?))

**Comment by sandarumk** [comment]
The information for the project is at https://github.com/systers/ossprojects/wiki/Peace-Corps-Safety-App
You can join the slack channel if you have more questions. http://systers.io/slack-systers-opensource/
There is a separate channel for #pcsa .
