### ISSUE TITLE
Correct link for Con App 

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/ossprojects#7]
@MeepyMay The link given in WIKI under GSOC-2017 for the ConApp should be updated to https://github.com/systers/ossprojects/wiki/Conference-App ,currently it takes to our home page.

**Comment by Jagruti1010** [comment]
@anubhakushwaha  it is correct only. Issue should be closed.

**Comment by anubhakushwaha** [comment]
@Jagruti1010 Thanks for updating me,the link was not correct while creating the issue :) Closing.
