### ISSUE TITLE
Idea about App

### ISSUE THREAD

**Issue by Prem0707** [systers/ossprojects#8]
Is it like this?
The project aims at developing an Android Framework which allows organizers to create apps for conferences and events. Using this framework, the organizers can create apps for any event, conference or meetup by creating and adding data in the configuration file (XML) from a static web page.

@MeepyMay Can you please elaborate the idea of the app? Is it included in GSoC'17?

**Comment by Jagruti1010** [comment]
@MeepyMay  I Think , We should create a stable App , which does not use only static Web page(WebView) , but should also use various designs and adapters, to Give our app a better look.
