### ISSUE TITLE
compile errors in maleria-ios application

### ISSUE THREAD

**Issue by rathishubham7** [systers/ossprojects#9]
I cloned the maleria-ios repo . after converting the code to latest syntax(2.3 to 3 ) , the application shows compile time errors . i tried to link the pods but still getting the same error . @MeepyMay @sandarumk

**Comment by sandarumk** [comment]
You should report these kind of issues in the specific repo it self. Not here. When reporting issues, please read the READ ME of the specific repo and follow the guidelines. You can also join the slack channel and ask the questions there as well.
